README.md
Installation method has changed.
=> Updated install instructions for Kubeless

deploy/kubelessDeploy.js, package.json, test/kubelessDeploy.test.js, test/lib/serverless.js
We were using the handler file present in `cwd` so we were ignoring the `--package` option when given.
=> Fix --package option for deploy method. Fix returned value in tests

LICENSE, deploy/kubelessDeploy.js, index.js, invoke/kubelessInvoke.js, lib/helpers.js, logs/kubelessLogs.js, provider/kubelessProvider.js, remove/kubelessRemove.js, test/kubelessInvoke.test.js, test/kubelessLogs.test.js, test/lib/serverless.js
just to show how to fix https://github.com/serverless/serverless-kubeless/issues/1 quickly
=> add ASL v2 license headers

README.md
The changes in the README adapt the commands and the module name to the version 0.1.0
=> Adapt README to version 0.1.0

deploy/kubelessDeploy.js, package.json, test/kubelessDeploy.test.js
This PR adds support for having a file `requirements.txt` next to the handler file to install those requirements for the deployed function.
=> Add dependencies support

deploy/kubelessDeploy.js, test/kubelessDeploy.test.js
This PR improves the UX since right now we are not waiting for the function to be deployed before giving back the control to the user:
```
$ sls deploy && sls invoke -f hello
Serverless: Packaging service...
Serverless: Function hello succesfully deployed
Serverless: Calling function: hello...
Serverless Error ---------------------------------------
Service Unavailable
```
but with these changes:
```
$ sls deploy && sls invoke --verbose -f hello
Serverless: Packaging service...
Serverless: Waiting for function hello to be fully deployed. Pods status: {"waiting":{"reason":"PodInitializing"}}
Serverless: Function hello succesfully deployed
Serverless: Calling function: hello...
--------------------------------------------------------------------
hello world!
```
=> Wait for a function deployment before exiting

examples/get-ruby/README.md, examples/get-ruby/package.json, examples/get-ruby/serverless.yml, examples/get-ruby/version.rb, examples/post-ruby/README.md, examples/post-ruby/package.json, examples/post-ruby/ping.rb, examples/post-ruby/serverless.yml
These examples won't work until there is a new release of `kubeless` including https://github.com/kubeless/kubeless/pull/212. I manually applied the changes to implement the examples.
=> Ruby examples

logs/kubelessLogs.js, test/kubelessLogs.test.js
`sls logs --tail` command was still flaky since depending the time in which the command is called the function entered in a race condition in which most of the log entries were skipped.
For fixing it we have switched the approach to directly call the Kubernetes API for retrieving the logs  but opening a stream to continuously fetch the data (`/api/v1/namespaces/default/pods/podname/log?follow=true`).
That way the logic is more simple and we don't need keep track of the delta of logs.
=> Change approach for retrieving logs when tailing

deploy/kubelessDeploy.js, test/kubelessDeploy.test.js
Retry if the API request times out when trying to retrieve logs info.
Fixes #36
=> Retry request when timed out

info/kubelessInfo.js, test/kubelessInfo.test.js
when any function has not been deployed yet show a message saying `Not found any information about the function foobar`
=> Show proper message when no info is available

lib/helpers.js, test/helpers.test.js
=> Add support for OIDC id-token

lib/get-logs.js, test/kubelessLogs.test.js
Issue Ref: https://github.com/serverless/serverless-kubeless/issues/85#issuecomment-347333276
=> Avoid to access pods with empty labels

examples/todo-app/backend/README.md
=> Update TODO app readme

lib/helpers.js, package.json
=> Avoid SSL without certificate-authority

package-lock.json, package.json, test/kubelessDeploy.test.js
=> Update npm deps

.travis.yml, package-lock.json, package.json
=> Update mocha version

deploy/kubelessDeploy.js, lib/deploy.js, test/kubelessDeploy.test.js
=> Allow env vars in the provider section

.travis.yml, deploy/kubelessDeploy.js, package.json, scripts/integration-tests.sh
=> Add artifact path

.travis.yml
=> Refresh token

lib/deploy.js, lib/helpers.js, lib/remove.js, package-lock.json, package.json, test/examples-test.js, test/helpers.test.js, test/kubelessDeploy.test.js
this fixes #162 
the trigger name will be correctly escaped and changed to a dash separated lowercase name to support deployment of functions that relay on camelCase named kafka topics
=> escapeName helper method deals correctly with camelcase names

lib/config.js, lib/helpers.js
Fixes #168 
Added a null check for `userInfo.user['auth-provider'].config.expiry` and error handling for Kubeless config requests that return unauthorized.
=> Fixed access-token expiry issues and improved error handling

lib/config.js, test/config.test.js
=> Check an env var for the kubeless namespace when searching for the config map.

deploy/kubelessDeploy.js, examples/post-php-s3/README.md, examples/post-php-s3/handler.php, examples/post-php-s3/package.json, examples/post-php-s3/serverless.yml, lib/deploy.js, lib/strategy.js, lib/strategy/base64_zip_content.js, lib/strategy/s3_zip_content.js, package-lock.json, package.json, scripts/integration-tests.sh, test/examples-test.js, test/kubelessDeployStrategy.test.js, test/minio.yml
I'd like to be able to define in which way function should be deployed (either as `zip+base64` or as `url+zip`)
for that, i'm going to implement deployment strategy, which will upload function .zip to s3 bucket and then replace `f.content` with actual url
not going to implement advanced functionality like deleting old .zips etc, just a pretty basic stuff
what community thinks about it?
=> added url+zip deploy method

deploy/kubelessDeploy.js, package.json, test/kubelessDeploy.test.js
Add the ability to deploy pre-packaged individual functions, details can be found in #190
=> Add Support for individually prepackaged functions
