serverless/serverless-kubeless

- index.js
- logs/kubelessLogs.js
- test/kubelessInvoke.test.js
- test/kubelessLogs.test.js
This PR adds support for the `logs` command and the following options:
```
Plugin: KubelessLogs
logs .......................... Output the logs of a deployed function
--function / -f (required) ......... The function name
--tail / -t ........................ Tail the log output
--startTime ........................ Logs before this time will not be displayed
--filter ........................... A filter pattern
--interval / -i .................... Tail polling interval in milliseconds. Default: `1000`
--count / -n ....................... Number of lines to print
```
> Add support to 'logs' command

- deploy/kubelessDeploy.js
- remove/kubelessRemove.js
- test/kubelessDeploy.test.js
- test/kubelessRemove.test.js
- test/lib/serverless.js
Before this PR the serverless.yaml file should contain as a service name the name of the function we want to deploy. With this change we add support for deploying and removing several functions using the same serverless definition.
We also cover the code for this two methods with unit tests.
> Fix deploy and remove actions for multiple functions. Add tests

- logs/kubelessLogs.js
This PR fixes a race condition in which if the time to retrieve the log is long and the checking interval is short the logs were not being printed.
I unsuccessfully tried to add a unit test for this fix. There is not an easy way to stub the `console.log` call inside the `printLogs().then(` function since it runs in a different context due to the promise.
> Fix log printing for short intervals

- examples/package.json
- examples/serverless.yml
- info/kubelessInfo.js
- package.json
- test/kubelessDeploy.test.js
- test/kubelessInfo.test.js
- test/kubelessRemove.test.js
Prepare the code for the release of the version 0.1.0
Add the license header for the files that lacked of it.
> Bump version to 0.1.0. Rename the npm name to serverless-kubeless.

- .gitignore
- README.md
- deploy/kubelessDeploy.js
- deployFunction/kubelessDeployFunction.js
- info/kubelessInfo.js
- invoke/kubelessInvoke.js
- lib/helpers.js
- logs/kubelessLogs.js
- package.json
- remove/kubelessRemove.js
- test/helpers.test.js
- test/kubelessDeploy.test.js
- test/kubelessInfo.test.js
- test/kubelessInvoke.test.js
- test/kubelessLogs.test.js
- test/kubelessRemove.test.js
- test/lib/load-kube-config.js
- test/lib/rm.js
This PR adds support for different Kubernetes cluster providers apart from Minikube like GKE or AWS EC2.
For doing so it reads the cluster information from the Kubernetes configuration located at `$HOME/.kube/config` or any path specified in the env var `$KUBECONFIG`. From these files we need:
- Current context.
- Kubernetes API URL. There is no need to specify this URL with an env var anymore.
- Authentication info. We can authenticate our request against the cluster using three different methods:
- Using a token.
- Using username and password.
- Using a certificate and a key.
After gathering that information we are able to connect to the cluster independently of its provider.
> Support for different kubernetes platforms

- deploy/kubelessDeploy.js
- package.json
- test/kubelessDeploy.test.js
This PR adds support for NodeJS and Ruby functions. For adding dependencies it will look for a `package.json` file in case of NodeJS and a `Gemfile` file in case of Ruby.
Note that Ruby functions won't work until https://github.com/kubeless/kubeless/issues/209 is fixed.
> Add support for NodeJS and Ruby functions

- README.md
- deploy/kubelessDeploy.js
- deployFunction/kubelessDeployFunction.js
- index.js
- package.json
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
This PR adds support for the command `deploy function -f <func_name>` that allows users to update their functions easily.
The existing code of the command `deploy` has been slightly refactored so we are able to inherit from it in the new command.
> Add support for 'deploy function' command

- deploy/kubelessDeploy.js
- info/kubelessInfo.js
- invoke/kubelessInvoke.js
- lib/helpers.js
- logs/kubelessLogs.js
- remove/kubelessRemove.js
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/kubelessInfo.test.js
- test/kubelessInvoke.test.js
- test/kubelessLogs.test.js
- test/kubelessRemove.test.js
- test/lib/serverless.js
This PR enable users to specify different namespaces than the default when deploying a function. They can choose a namespace per service or per function. As an example:
```
service: hello
provider:
name: google
namespace: test
runtime: python2.7
plugins:
- serverless-kubeless
functions:
hello:
handler: handler.hello
hello2:
namespace: test2
handler: handler.hello
```
That would deploy the function `hello` in the namespace `test` and the function `hello2` in the namespace `test2`
This completes #26
> Add support for custom Namespaces

- deploy/kubelessDeploy.js
- examples/event-trigger-python/README.md
- examples/event-trigger-python/handler.py
- examples/event-trigger-python/package.json
- examples/event-trigger-python/serverless.yml
- package.json
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
This PR enable users to define a topic for triggering their functions.
Note that the `function.events` object should be an array to follow serverless conventions but it is not supported to specify more than one event source for the same function in kubeless.
> Add event trigger support

- README.md
- deploy/kubelessDeploy.js
- info/kubelessInfo.js
- test/kubelessDeploy.test.js
- test/kubelessInfo.test.js
This PR adds the possibility of defining a `Description` and `Labels` fields in function metadata. The user could define:
serverless.yml:
```
functions:
hello:
handler: handler.hello
description: 'This is a test!'
labels:
test: 'hello'
```
And that information would be shown with the `info` command:
```
Function Info
Description: This is a test!
Labels:
test: hello
Handler:  handler.hello
```
It also fixes how we show the information about the function trigger source.
> Add metadata fields description and labels

- deploy/kubelessDeploy.js
- deployFunction/kubelessDeployFunction.js
- examples/http-custom-path/README.md
- examples/http-custom-path/handler.py
- examples/http-custom-path/package.json
- examples/http-custom-path/serverless.yml
- info/kubelessInfo.js
- logs/kubelessLogs.js
- package.json
- remove/kubelessRemove.js
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/kubelessInfo.test.js
- test/kubelessRemove.test.js
This PR adds support for deploying functions in a specific path. This is needed to solve #33.
It does require to have an Ingress Controller running. I used the one available at https://github.com/kubeless/kubeless/blob/master/manifests/ingress/ingress-controller.yaml.
It also includes an example for deploying a function under a certain path.
> Add support for HTTP custom paths

- deploy/kubelessDeploy.js
- test/kubelessDeploy.test.js
Allow to specify the path in the `serverless.yaml` file as a relative path.
Fixes related unit tests.
> Allow relative paths in events.http.path

- README.md
- deploy/kubelessDeploy.js
- examples/event-trigger-python/serverless.yml
- examples/get-python/serverless.yml
- examples/get-ruby/serverless.yml
- examples/http-custom-path/serverless.yml
- examples/multi-python/serverless.yml
- examples/post-nodejs/serverless.yml
- examples/post-python/serverless.yml
- examples/post-ruby/serverless.yml
- info/kubelessInfo.js
- invoke/kubelessInvoke.js
- logs/kubelessLogs.js
- package.json
- provider/kubelessProvider.js
- remove/kubelessRemove.js
Change the `google` references with `kubeless`. This requires a serverless version `>1.19.0`.
> Set provider to kubeless

- deploy/kubelessDeploy.js
- test/kubelessDeploy.test.js
This PR enable users to specify a memory limit and environment variables on its functions.
The memory limit can be set per service or per function. Environment variables are function specific.
Issue ref: #33
It depends on https://github.com/kubeless/kubeless/pull/217 so for testing this PR is necessary to build kubeless from master.
For a `serverless.yaml`:
```
service: hello
provider:
name: google
runtime: python2.7
plugins:
- serverless-kubeless
functions:
hello:
handler: handler.hello
environment:
TEST: 1
memorySize: 128Mi
```
it deploys a function:
```
spec:
deps:
function: |
def hello():
return "hello world"
handler: handler.hello
runtime: python2.7
template:
spec:
containers:
- env:
- name: TEST
value: "1"
name: hello
resources:
limits:
memory: 128Mi
requests:
memory: 128Mi
type: …
```
> Add support for memory limit and env vars

- deploy/kubelessDeploy.js
- examples/http-custom-path/README.md
- examples/todo-app/README.md
- examples/todo-app/backend/README.md
- examples/todo-app/backend/todos-create.js
- examples/todo-app/backend/todos-delete.js
- examples/todo-app/backend/todos-read-all.js
- examples/todo-app/backend/todos-read-one.js
- examples/todo-app/backend/todos-update.js
- examples/todo-app/frontend/react-redux/README.md
- examples/todo-app/frontend/react-redux/app/js/actions/index.js
- examples/todo-app/frontend/react-redux/app/js/actions/todos.js
- info/kubelessInfo.js
- ingress-controller-http-only.yaml
- ingress-controller.yaml
- package.json
- test/kubelessDeploy.test.js
- test/kubelessInfo.test.js
To avoid using HTTPS it is necessary to use a hostname when adding an Ingress rule. In this diff we add support for specifying a hostname when deploying a function, we point to the latest ingress manifest available in Kubeless (HTTP only) and we adapt the examples to this new approach. If it is not specified, the functions will be deployed with a hostname `API_URL.nip.io` (being API_URL the URL of the Kubernetes API).
> Allow to use hostname when deploying an http function

- deploy/kubelessDeploy.js
- deployFunction/kubelessDeployFunction.js
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/lib/mocks.js
This PR adds support to:
- `sls deploy --force`: Redeploys the functions in the `server less.yaml` file even if they have been already deployed
- `sls deploy function -f func`: Apart from redeploying a function it will deploy if it has not been deployed yet.
It also includes a bit of a refactor in the test files.
Fixes #52
> Add support for forcing redeployments

- examples/multi-python/README.md
Changed `servereless` to `serverless`
> Problem: Typo in `serverless` command

- deploy/kubelessDeploy.js
- examples/event-trigger-python/README.md
- info/kubelessInfo.js
- invoke/kubelessInvoke.js
- lib/deploy.js
- lib/get-info.js
- lib/get-logs.js
- lib/helpers.js
- lib/invoke.js
- lib/remove.js
- logs/kubelessLogs.js
- package.json
- remove/kubelessRemove.js
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/kubelessInfo.test.js
- test/kubelessInvoke.test.js
- test/kubelessLogs.test.js
- test/kubelessRemove.test.js
- test/lib/mocks.js
- test/lib/serverless.js
This PR  split the serverless specific logic from the kubeless one in order to make the code reusable.
> Move logic into library files

- lib/deploy.js
- lib/functions.js
- lib/get-info.js
- lib/remove.js
- package.json
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/kubelessInfo.test.js
- test/kubelessRemove.test.js
- test/lib/mocks.js
ThirdpartyResources are deprecated. In this PR, following Kubeless, we have migrated the API requests to create CustomResources.
This requires Kubernetes >= 1.7
> Use Custom Resources instead of Thirdparty

- lib/deploy.js
In my cluster `serverless deploy` throws a exception when detecting the pods after deployment is finished.
Here is the screenshot.
After some checking I found out there are some pods in my cluster do not have the property 'metadata.labels', so I added some checking before it is being referenced.
I don't have much experience in Javascript, please feel free to tell me if the fix is not appropriate.
> Check 'pod.metadata.labels' exists before using it

- lib/deploy.js
- test/kubelessDeploy.test.js
This fix allows the user to mount secrets/configmaps as env var.
Before the fix one specifies key/value pairs as a dictionary:
```
environment:
FOO: BAR
PASSWORD: xxxxx
```
After the fix the value of 'environment' key is directly passed to k8s,
which allows for:
```
environment:
- name: FOO
value: BAR
- name: PASSWORD
valueFrom:
secretKeyRef:
name: my-secret
value: my-password
```
> Make 'environment' schema compatible with k8s

- deploy/kubelessDeploy.js
- lib/deploy.js
- test/kubelessDeploy.test.js
Allow the user optionally specify custom runtime image with:
1. `service.provider.image`
2. `service.provider.functions.<function_id>.image`
The second one overrides the first one.
closes #81
> Add support for custom runtime image

- lib/helpers.js
This change fixes #93 
Added a conditional check for KUBECONFIG paths list delimiter based on OS to fix deployment issue from Windows. Tested locally.
> Fixing functions deployment issue from Windows

- deploy/kubelessDeploy.js
- lib/deploy.js
- test/kubelessDeploy.test.js
Kubeless now support to specify the function port and the maximum timeout for the function execution. This PR adapt the serverless.yaml syntax to accept those parameters.
> Add support for specifying port and timeout of functions

- deploy/kubelessDeploy.js
- lib/deploy.js
- scripts/install-minikube.sh
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/lib/mocks.js
Kubeless now support to use Zip files to upload functions. This PR adapts this plugin to use the serverless packaged file instead of using standalone code files. 
This PR includes a **breaking change**. By default we are omitting the `node_modules` folder but even if without that folder the Zip file is bigger than 1MB the deployment will fail. It is necessary to use the [`package.exclude`](https://serverless.com/framework/docs/providers/aws/guide/packaging/#exclude--include)  syntax in order to avoid it.
> Use serverless packaged zip. Skip node_modules

- deploy/kubelessDeploy.js
- examples/http-custom-path/README.md
- examples/http-custom-path/serverless.yml
- examples/todo-app/backend/serverless.yml
- lib/deploy.js
- lib/ingress.js
- test/kubelessDeploy.test.js
`nip.io` is currently down, causing the integration tests to fail. We should not force to use that choice for all the functions so this PR allows to change that.
I changed the DNS resolution from `nip.io` to `xip.io` in the existing examples so we fix integration tests.
> Allow to change DNS resolution from nip.io

- lib/deploy.js
- test/kubelessDeploy.test.js
In case you want to add some secrets to your kubeless function [PR 572](https://github.com/kubeless/kubeless/pull/572) you can specify them as list of secret names in a function description.
```functions:
test:
handler: handler.test
namespace: kubeles
secrets:
- experiment
```
> Add Secrets support

- lib/deploy.js
- package.json
- test/examples-test.js
- test/kubelessDeploy.test.js
- test/lib/mocks.js
Ref: https://github.com/serverless/serverless-kubeless/issues/85#issuecomment-390550917
Use always string as labels. Limit function selector to just the function name.
> Parse labels as strings

- test/examples-test.js
This test is failing in master but I am not able to reproduce the issue. Disabling it for the moment since it doesn't test any particular feature of the plugin.
> Disable TODO App example test

- deploy/kubelessDeploy.js
- lib/deploy.js
- lib/ingress.js
Adds super basic support for setting the ingress controller used to something other than `nginx` (we're using traefik)
This was discussed a little in #114.
> Allow setting a custom ingress controller

- lib/invoke.js
- package-lock.json
- package.json
- scripts/release.sh
- test/kubelessInvoke.test.js
Ref #132 
Since Kubernetes +1.10 the URL of the `proxy` subresource should be specified after the name (and port) of the service.
(This PR also contains unrelated changes to the release script).
> Use latest proxy endpoint

- lib/helpers.js
This is required for proper CI integration, as running `kubectl config use-context <blah> && serverless deploy` can potentially lead to race conditions between concurrent deployments.
> Allow overriding k8s config context

- lib/deploy.js
- test/kubelessDeploy.test.js
- test/kubelessDeployFunction.test.js
- test/lib/mocks.js
This makes it possible to use things like `kube2iam` which require annotations on the pod.
Eg.
```
functions:
myFn:
handler: handler.myFn
annotations:
iam.amazonaws.com/role: role-arn
```
> Allow setting per-function annotations

- deploy/kubelessDeploy.js
- lib/deploy.js
- test/kubelessDeploy.test.js
Hey @andresmgot
I put this together at the request of our DevOps engineer who suggested we have cpu limits defined for the serverless functions so they wouldn't be deprived of the necessary resources. I know the other serverless frameworks don't support this (e.g. https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/) but since kubeless is ran on a kubernetes cluster with a finite amount of resources, IMO it makes sense to me that we have the ability to declare this, so the cluster can add more nodes if necessary and not deprive a serverless function of the resources it needs.
> feat: Adding CPU limits

- README.md
- deploy/kubelessDeploy.js
- lib/deploy.js
- test/kubelessDeploy.test.js
We leverage some of the more granular controls of k8s, as such I'm expanding the surface area of the serverless kubeless APIs. I hope this is okay.
For more info on these pieces of functionality.
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
**/cc @andresmgot**
> feat: Adding affinity & tolerations

- examples/cert-manager-https/README.md
- examples/cert-manager-https/handler.py
- examples/cert-manager-https/package.json
- examples/cert-manager-https/serverless.yml
- lib/ingress.js
- package.json
Very simple changes just adding in code to handle a few additional ingress config options.
- ingress.additionalAnnotations: just extra annotations that get appended to the ingress annotations.
- ingress.tlsConfig: optional tls config for ingress.
> Added support for configuring tls for ingress and additional ingress annotations.

- lib/deploy.js
- lib/get-info.js
- lib/invoke.js
- package-lock.json
- package.json
- test/kubelessDeploy.test.js
- test/kubelessInfo.test.js
- test/kubelessInvoke.test.js
- test/lib/mocks.js
Fixes: #160
**Background**
The way our k8s access control is configured, users generally don't have permissions to list all pods or services in the cluster.
For example `GET /api/v1/pods` will fail with
`User "<user>" cannot list resource "pods" in API group "" at the cluster scope`
**Issue**
Deploying using `serverless deploy` itself works, but the deployment progress checks fail, as these use `/api/v1/pods` and `/api/v1/services`.
The deployment code is namespace-aware, so I think the progress checks should use the namespaced APIs, too, i.e. `/api/v1/namespaces/<namespace>/pods`.
> Namespace not used when getting services and pods

- lib/deploy.js
- package.json
- test/kubelessDeploy.test.js
Set affinity in the deployment spec instead of in the pod itself.
> Fix for affinity not being added to deployment spec

- examples/cert-manager-https/package.json
- examples/event-trigger-python/package.json
- examples/get-python/package.json
- examples/get-ruby/package.json
- examples/http-custom-path/package.json
- examples/multi-python/package.json
- examples/node-chaining-functions/package.json
- examples/post-go/package.json
- examples/post-nodejs/package.json
- examples/post-php/package.json
- examples/post-python/package.json
- examples/post-ruby/package.json
- examples/scheduled-node/package.json
- examples/todo-app/backend/package.json
Found that `cert-manager-https` example was not working due to reference to `^0.4.0` when support for `tlsConfig` and `additionalAnnotations` was not added until `0.6.1`. 
All examples had the same version, so I bumped it to the latest.
Fixes #166.
> Bumped package version to fix broken examples

- lib/deploy.js
It is followon pull request for https://github.com/kubeless/kubeless/pull/993
After updating runtime images to use non-root user it is become impossible to run functions on port 80. To fix this Service can map port 80 to target port 8080. To support this this pull request was prepared. It allows define `servicePort` to distinguish between container and service ports
> defines optional servicePort

- examples/custom-ingress/README.md
- examples/custom-ingress/handler.py
- examples/custom-ingress/package.json
- examples/custom-ingress/serverless.yml
- lib/ingress.js
- package-lock.json
- package.json
This PR lets users optionally specify an ingress name alongside the class, with the following syntax:
```
provider:
name: kubeless
ingress: 
class: "azure/application-gateway"
name: "appgw" # <- New!
```
This is necessary to support Azure's `Application Gateway Ingress Controller (AGIC)`, as its class `azure/application-gateway` contains a `/`, which is an illegal character in annotation names.
[See here for an example of the AGIC class](https://azure.github.io/application-gateway-kubernetes-ingress/tutorial/#ExposeServicesOverHTTP) 
[And here for an example of the (different) name AGIC has in annotations](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/)
> Adds support for separate ingress class and ingress names.

- deploy/kubelessDeploy.js
- lib/deploy.js
- package-lock.json
- package.json
- test/kubelessDeploy.test.js
Added support function level `runtime` override :
```yaml
service: my-service
provider: 
name: kubeless
runtime: nodejs8
functions:
myFunction1:
handler: nodejs10handler.handle
runtime: nodejs10
myFunction2:
handler: nodejs8handler.handle
```
Analog of the function `runtime` override in the AWS provider:
https://serverless.com/framework/docs/providers/aws/guide/functions#configuration
> Allow function level runtime override

- lib/helpers.js
- package.json
AWS EKS utilizes the kubeconfig support for [client-go credential plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) to execute the `aws` CLI command to receive user credentials when authenticating to an EKS cluster. This PR adds support to serverless-kubeless to use such configs as another access token mechanism and should address issue #140 
(Thanks to the [Javascript Kubernetes Client cloud_auth](https://github.com/kubernetes-client/javascript/blob/master/src/cloud_auth.ts) for the general idea of how to do this.)
> Add support for "dynamic" EKS token auth

- lib/helpers.js
- package.json
Thanks to contributors, dynamic EKS credentials have been supported since the following PRs(https://github.com/serverless/serverless-kubeless/pull/189, https://github.com/serverless/serverless-kubeless/pull/192).
However, the above commits did not properly passed the `AWS_PROFILE` value: `aws-iam-authenticator` breaks because it does not know the `--profile` argument. Thus, I created another envvar map for child process, put `AWS_PROFILE` value inside the map, and passed the map to the child process.
Passing `AWS_PROFILE` as an environment variable will not break `aws`.
> Pass AWS_PROFILE value as an environment variable

- .travis.yml
- lib/strategy/s3_zip_content.js
- package-lock.json
- package.json
Hello,
when I deploy a Kubeless function with strategy: S3ZipContent, the deploy fails.
The pod goes in Init:CrashLoopBackOff status because the Kubeless prepare initContainer cannot retrieve the artifact from the bucket using the S3 presigned url.
Logs of the prepare initContainer:
```
sh: 1: -L: not found
```
The issue seems related to the CURL command in the preapre container that has the url argument with two quotes before and after the url. 
Example:
```
curl ''https://grid.photosi.com/kubeless-artifacts-test/microservice-sls-test-1583329211862.zip?AWSAccessKeyId=XXXXX&Expires=1614865212&Signature=a%2Fc%2F5A3k3G0EbL%2Fz0Up9u8m6pN0%3D''
-L --silent --output /tmp/func.fromurl && echo 'f68e1c7f7427afdc65b4cdcd514239fdb3ffd4850cb00cd6032189305b9ee827  /tmp/func.fromurl'
> …
```
> remove shell-escaping url in S3ZipContent

- lib/helpers.js
- package.json
fixes #202 .
No problems with null depFile (see [this](https://github.com/serverless/serverless-kubeless/blob/a31d1282213763ec4ada914324d254291699d9d9/deploy/kubelessDeploy.js#L123)).
> remove depFile check,  dependency file is not mandatory in Kubeless runtimes

- lib/helpers.js
- package-lock.json
- package.json
> Attach env vars from kube config when renewing token

- lib/deploy.js
- package.json
- test/kubelessDeploy.test.js
- test/lib/mocks.js
The "waitForDeployment" method in deploy.js module is waiting for running function pods before creating other resources (eg triggers).
It should also waits for the presence of the service used by the deployed function.
Without this pull request the creation of some resource could fail. Thus the creation of an HTTP Trigger sometimes fails because the function is deployed but the service isn't.
> waitForDeployment should also waits for service presence

- lib/deploy.js
- lib/helpers.js
- package-lock.json
- package.json
This pull request replace the current setInterval implementation with an exponential check (30 seconds of max check delay).
This type of check permits a longer wait period without flooding the kubernetes master.
A longer wait period is required for service with a considerable number of functions and with a runtime that needs a build step (.net, java, ...).
> New waitForDeployment check logic

- lib/deploy.js
Hello,
Currently labels specified in a function declaration in serverless.yml ([https://www.serverless.com/framework/docs/providers/kubeless/guide/functions#labels](https://www.serverless.com/framework/docs/providers/kubeless/guide/functions#labels)) are set to all the Kubernetes resources related to that function (pods, deployment, service and Function CRD) except for the function trigger CRD.
With this PR we set these labels also to the function trigger CRD.
> Add labels specified in serverless.yml functions to triggers

- .travis.yml
- lib/deploy.js
- package.json
A deploy of a service with a lot of functions could results in an high cpu/ram/io pressure for a k8s infrastructure.
Think to a dotnet service with twenty function, for instance. When you deploy this service, kubeless creates twenty build pod at the same time.
With this pull request you can set an environment variable to deal with deploy concurrency.
As example:
```
export DEPLOY_CONCURRENCY=2
serverless deploy
```
The functions will be deployed two at a time.
> Add ability to set function deploy concurrency

- lib/invoke.js
- package.json
- test/kubelessInvoke.test.js
I had this issue that I could invoke functions only in the `default` namespace, if I deploy in other namespaces it will fail to be invoked
I noticed that when you create a new serverless project with the command:
`serverless create --template kubeless-nodejs --path new-project` works fine, you can deploy in every namespace and can invoke the functions.
If you check in package.json it uses serverless-kubeless v0.4.0. I've tested and everything works fine up to version 0.6.0
In the new versions of serverless-kubeless it doesn't work. The only difference I found between versions was that in invoke.js on line 115 the function was changed from `core.services.get` => `core.ns.services.get`
If you remove `ns` it works fine again.
> fix unable to run function in other namespaces

- lib/deploy.js
- package.json
- test/kubelessDeploy.test.js
Right now the tolerations aren't included in the yaml of
the Pods created by the Deployment. Moving them into the
PodTemplateSpec is fixing this.
> Move tolerations to PodTemplateSpec
